### ISSUE TITLE
Magazine repack

### ISSUE THREAD

**Issue by jmlane** [jmlane/Asymmetric.Altis#1]
Requested by @Diffusion9 and seconded by Crake.

**Comment by ghost** [comment]
[Outlawled's mag repack](http://www.armaholic.com/page.php?id=19692); also leverages CBA.

**Comment by jmlane** [comment]
ACE's mag repack is functional. Considering the emerging trend of just using a bunch of ACE feature, I'm not interested in a mission script based alternative at this point.
