### ISSUE TITLE
Custom objectives can spawn units into bad places

### ISSUE THREAD

**Issue by jmlane** [jmlane/Asymmetric.Altis#11]
This spawning issue seems to be most obvious when the ALiVE profiling system initializes and places units, within "render" distance to players, in a bad position in the world. The results range from stuck to exploding units.

The custom objectives in the FIA starting area are particularly bad for this. Moving the modules away from bad geometry or reducing the size might help reduce the number of bad spawns.

**Comment by ghost** [comment]
Can you see if it uses BIS_fnc_findsafepos (or something similar)? If it does you could modify the incoming params to increase the target safePOS area if its colliding with geometry or something.

**Comment by jmlane** [comment]
The spawning does use something similar but it's not really working well with custom placed objects and the weird geometry near Thronos castle.

Moving the custom military module marker and not spawning motorized units in those map areas seems to have fixed the issue in 0949fe0.
