### ISSUE TITLE
Earplugs

### ISSUE THREAD

**Issue by jmlane** [jmlane/Asymmetric.Altis#2]
Requested by @Diffusion9

**Comment by ghost** [comment]
+1
If you throw the code up at some point, I can implement a Supports Menu earplug similar to Athena if you wanted. Its a pretty simple thing: literally just a [fadeSound](https://community.bistudio.com/wiki/fadeSound) command nested in an IF\THEN

**Comment by jmlane** [comment]
I really like the ACE implementation of earplugs, but mostly because of the neat combat deafness feature. I'd rather have that than a mission-specific implementation.
