### ISSUE TITLE
Restrict FIA Arsenal box to cosmetic and faction specific gear

### ISSUE THREAD

**Issue by jmlane** [jmlane/Asymmetric.Altis#3]

**Comment by ghost** [comment]
Only thing I don't like about Arsenal is that you can't limit the number of items to equip.  Which, I suppose isn't really an issue for cosmetic stuff. But if you wanted only a specific number of vests or whathaveyou you can't really do that from within Arsenal -- it appears to be an infinite-or-nothing sort of thing.

**Comment by jmlane** [comment]
Resolved by 4a67757
