### ISSUE TITLE
Remove 2D task/custom waypoint indicators

### ISSUE THREAD

**Issue by jmlane** [jmlane/Asymmetric.Altis#4]
This is a minor issue but it would ensure players are using land-nav skills.

**Comment by ghost** [comment]
Which 2D markers do you mean, here? The ones that show up when you get a mission that indicate where its at? The little circle-marker-type-thing? 

I thiiink you can disable them with _taskManagement_markers2D_ and _taskManagement_markers3D_ in description.ext. [BIS Wiki](https://community.bistudio.com/wiki/Description.ext#taskManagement_markers2D).

**Comment by jmlane** [comment]
Yup, that's what I'm referring to. There are a bunch of HUD and indicator things I'd want to tweak but I need to focus on things that reduce the amount of awareness and premeditation required of players as a priority.

**Comment by jmlane** [comment]
I thought this was determined by [.Arma3Profile difficulty setting _hudWp_](https://community.bistudio.com/wiki/Arma_3_Difficulty_Menu#HUD_waypoints_info) but setting that to zero didn't seem to work in my last test. I'm going to have to dig into it a bit more.

**Comment by jmlane** [comment]
Fixed on Kobol Gaming server... I was using `-profiles=path` but didn't have the .arma3profile file in the proper `path/Users/<username>/` path.
